### ISSUE TITLE
Milestone 2 Feedback: Reasoning

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_Group_404#40]
For your report to be complete, you should:
- [x] interpret the findings/results in context of the question
- [x] provide some critique of your analysis, i.e. what might be some limitations regarding the analysis or the data?
- [x] provide a statement of future directions.

**Comment by lori94** [comment]
finished
