### ISSUE TITLE
Milestone 3 Feedback: Mechanics

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_Group_404#52]
- [x] You can remove the links to previous releases from the main README as these are no longer necessary here.
- [x] Please add commands related to Make in the usage information on your main README.
- [x] Do not forget to close the issues that have been addressed so that you do not have so many open issues in your repo.
